# Generated by Django 6.0.2 on 2026-02-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('unidade', models.CharField(max_length=20, verbose_name='Unidade (kg, fardo, saco...)')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Insumo',
                'verbose_name_plural': 'Tipos de Insumo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do fornecimento')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço unitário (R$)')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total (R$)')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('faturado', models.BooleanField(default=False, verbose_name='Faturado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='contratos.contrato', verbose_name='Contrato')),
                ('tipo_insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.tipoinsumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Lançamento de Insumo',
                'verbose_name_plural': 'Lançamentos de Insumos',
                'ordering': ['-data'],
            },
        ),
    ]
