# Generated by Django 6.0.2 on 2026-02-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField(verbose_name='Mês de referência')),
                ('ano_referencia', models.IntegerField(verbose_name='Ano de referência')),
                ('data_vencimento', models.DateField(verbose_name='Data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do aluguel (R$)')),
                ('valor_insumos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de insumos (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total (R$)')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='contratos.contrato', verbose_name='Contrato')),
                ('lancamentos', models.ManyToManyField(blank=True, to='insumos.lancamentoinsumo', verbose_name='Lançamentos de insumos')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturas',
                'ordering': ['-ano_referencia', '-mes_referencia'],
                'unique_together': {('contrato', 'mes_referencia', 'ano_referencia')},
            },
        ),
    ]
