# Generated by Django 6.0.2 on 2026-02-19 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Nº do Contrato')),
                ('tipo', models.CharField(choices=[('baia', 'Baia'), ('pasto', 'Pasto'), ('baia_pasto', 'Baia + Pasto'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de aluguel')),
                ('identificacao_local', models.CharField(blank=True, max_length=100, verbose_name='Identificação (ex: Baia 3, Pasto A)')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor mensal (R$)')),
                ('dia_vencimento', models.IntegerField(default=10, verbose_name='Dia de vencimento')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('suspenso', 'Suspenso')], default='ativo', max_length=20, verbose_name='Status')),
                ('clausulas_extras', models.TextField(blank=True, verbose_name='Cláusulas adicionais')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.animal', verbose_name='Animal')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
