# Generated by Django 6.0.2 on 2026-02-19 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='valor_mensal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor mensal (R$)'),
        ),
        migrations.CreateModel(
            name='ItemContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('aluguel', 'Aluguel'), ('racao', 'Ração'), ('feno', 'Feno'), ('serragem', 'Serragem'), ('servico', 'Serviço / Mão de obra'), ('outro', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(blank=True, default='mês', max_length=30, verbose_name='Unidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitário (R$)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal (R$)')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Item do Contrato',
                'verbose_name_plural': 'Itens do Contrato',
                'ordering': ['categoria'],
            },
        ),
    ]
